version: '3.8'
services:
  app:
    image: maven:3.9.11-eclipse-temurin-17
    working_dir: /app
    volumes:
      - .:/app
    command: mvn spring-boot:run
    environment:
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - GOOGLE_API_CX=${GOOGLE_API_CX}
    ports:
      - "8080:8080"
